pipeline {
    agent any

    // Monday to Friday, between 9 & 9:59
    triggers { cron('H 9 * * 1-5') }

    // Environment Variables
    environment {
        AWSKLEAN_AWS_ACCOUNT_NUMBERS="1111111111,222222222,3333333333,44444444"
        AWSKLEAN_DAY_RANGE=3
        AWSKLEAN_ROLE_NAME="awsklean"
    }

    stages {
        // List Accounts that have access methods that haven't been used within day range and will be actioned
        stage("List IAM users that have access methods not used in day range & notify slack (SIBLING(S))"){
            steps{
                // Set default IAM credential for awsklean to use to access base AWS accoun
                withCredentials([usernamePassword(credentialsId: 'awsklean-default-iam-credentials', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable:'AWS_SECRET_ACCESS_KEY')]){
                    // Set slack webhook for awsklean to use
                    withCredentials([string(credentialsId: 'awsklean-slack-webhook', variable: 'AWSKLEAN_SLACK_WEBHOOK')]){
                        sh """
                            /bin/bash awsklean_wrapper.sh \"--aws-account-numbers\" \"${env.AWSKLEAN_AWS_ACCOUNT_NUMBERS}\" \"--aws-profile\" \"${env.AWSKLEAN_ROLE_NAME}\" \"--passthrough\" \"-l,${env.AWSKLEAN_DAY_RANGE}:--notify-slack:\"
                        """
                    }
                }
            }
        }

        // Sleep for 5 minutes to allow users to cancel pipeline
        stage("Sleep for 5 seconds to allow user to cancel pipeline"){
            steps{
                sh """
                    sleep 300
                """
            }
        }

        // List Accounts that have access methods that haven't been used within day range and will be actioned
        stage("Deactivate access method(s) for users that fall outside of range"){
            steps{
                // Set default IAM credential for awsklean to use to access base AWS accoun
                withCredentials([usernamePassword(credentialsId: 'awsklean-default-iam-credentials', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable:'AWS_SECRET_ACCESS_KEY')]){
                    // Set slack webhook for awsklean to use
                    withCredentials([string(credentialsId: 'awsklean-slack-webhook', variable: 'AWSKLEAN_SLACK_WEBHOOK')]){
                        sh """
                            /bin/bash awsklean_wrapper.sh \"--aws-account-numbers\" \"${env.AWSKLEAN_AWS_ACCOUNT_NUMBERS}\" \"--aws-profile\" \"${env.AWSKLEAN_ROLE_NAME}\" \"--passthrough\" \"-d,${env.AWSKLEAN_DAY_RANGE}:--notify-slack:\"  
                        """
                    }
                }
            }
        }
    
    }
}